services:
  grafana:
    environment:
    - GF_SECURITY_ADMIN_PASSWORD=admin
    image: grafana/grafana:latest
    ports:
    - 3000:3000
    volumes:
    - grafana_data:/var/lib/grafana
  phomem-cosim:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
    - ENVIRONMENT=development
    - LOG_LEVEL=DEBUG
    - OPTIMIZATION_LEVEL=balanced
    ports:
    - 8000:8000
    - 9090:9090
    restart: unless-stopped
    volumes:
    - ./logs:/app/logs
  prometheus:
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    image: prom/prometheus:latest
    ports:
    - 9091:9090
    volumes:
    - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
version: '3.8'
volumes:
  grafana_data: {}
